#!/usr/bin/env python3
"""Generate the installed-user aesthetic index from dictionary frontmatter."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from validation_common import split_frontmatter

REPO_ROOT = Path(__file__).resolve().parent.parent
DICTIONARY_DIR = REPO_ROOT / "skills" / "aesthetic-literacy" / "aesthetics"
INDEX_PATH = REPO_ROOT / "skills" / "aesthetic-literacy" / "references" / "aesthetic-index.md"


@dataclass(frozen=True)
class Entry:
    slug: str
    label: str
    family: str
    aliases: tuple[str, ...]
    redirect: str | None


def _string_list(value: object) -> tuple[str, ...]:
    if not isinstance(value, list):
        return ()
    return tuple(str(item) for item in value if isinstance(item, str) and item.strip())


def load_entries(dictionary_dir: Path = DICTIONARY_DIR) -> list[Entry]:
    entries: list[Entry] = []
    for path in sorted(dictionary_dir.glob("*.md")):
        frontmatter, _ = split_frontmatter(path)
        if frontmatter is None or "__frontmatter_type_error__" in frontmatter:
            raise ValueError(f"{path} is missing valid YAML frontmatter")

        slug = frontmatter.get("slug")
        label = frontmatter.get("label")
        family = frontmatter.get("family")
        if not isinstance(slug, str) or not isinstance(label, str) or not isinstance(family, str):
            raise ValueError(f"{path} must declare string slug, label, and family")
        redirect_value = frontmatter.get("redirect") or frontmatter.get("superseded_by")
        redirect = redirect_value if isinstance(redirect_value, str) and redirect_value.strip() else None
        entries.append(
            Entry(
                slug=slug,
                label=label,
                family=family,
                aliases=_string_list(frontmatter.get("aliases")),
                redirect=redirect,
            )
        )
    return entries


def render_index(entries: list[Entry]) -> str:
    full_entries = [entry for entry in entries if entry.redirect is None]
    redirects = [entry for entry in entries if entry.redirect is not None]
    by_family: dict[str, list[Entry]] = defaultdict(list)
    for entry in full_entries:
        by_family[entry.family].append(entry)

    lines = [
        "# Aesthetic Index",
        "",
        "<!-- Generated by scripts/generate_aesthetic_index.py; do not edit by hand. -->",
        "",
        "Skill-local lookup index for installed users. Use this file to find the canonical slug, then load `../aesthetics/<slug>.md` for the complete dictionary entry. Keep root `knowledge/aesthetics/` research profiles out of normal app-design workflows unless provenance, maintenance, or research detail is explicitly requested.",
        "",
        f"- Full entries: {len(full_entries)}",
        f"- Redirect entries: {len(redirects)}",
        f"- Families: {len(by_family)}",
        "",
        "## Lookup rules",
        "",
        "1. Match the user's named aesthetic or alias to a slug below.",
        "2. Load `aesthetics/<slug>.md` relative to `aesthetic-literacy/SKILL.md` before characterizing or applying that aesthetic.",
        "3. For redirects, follow the target slug and load the target entry instead.",
        "4. Do not load root research logs for routine app design; use them only for provenance, maintenance, or research tasks.",
        "",
    ]

    for family in sorted(by_family):
        family_entries = sorted(by_family[family], key=lambda entry: entry.slug)
        lines.extend([f"## {family}", ""])
        lines.append("| Slug | Label | Aliases |")
        lines.append("| --- | --- | --- |")
        for entry in family_entries:
            aliases = ", ".join(entry.aliases) if entry.aliases else "—"
            lines.append(f"| `{entry.slug}` | {entry.label} | {aliases} |")
        lines.append("")

    if redirects:
        lines.extend(["## Redirects / Superseded Entries", ""])
        lines.append("| Slug | Label | Target |")
        lines.append("| --- | --- | --- |")
        for entry in sorted(redirects, key=lambda item: item.slug):
            lines.append(f"| `{entry.slug}` | {entry.label} | `{entry.redirect}` |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated index is stale")
    args = parser.parse_args()

    rendered = render_index(load_entries())
    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current != rendered:
            print(f"{INDEX_PATH.relative_to(REPO_ROOT)} is stale; run scripts/generate_aesthetic_index.py")
            sys.exit(1)
        print("aesthetic-index.md is current")
        return

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
